// Design tokens → CSS custom properties (src/design/tokens.css) and a typed module (src/design/tokens.ts).
// Run by `npm run dev` / `npm run build` (pre-scripts) or `npm run tokens`. Output is ignored by Git.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "src", "design");
const tokens = JSON.parse(readFileSync(join(src, "tokens.json"), "utf8"));

const css = [];
function walk(node, path) {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$") || k === "contrast") continue;
    const p = [...path, k];
    if (v && typeof v === "object") walk(v, p);
    else css.push(`  --${p.join("-")}: ${v};`);
  }
}
walk(tokens, []);
const header = "/* Generated by scripts/build-tokens.mjs from tokens.json — do not edit. */\n";
writeFileSync(join(src, "tokens.css"), `${header}:root {\n${css.join("\n")}\n}\n`);

const ts = `// Generated by scripts/build-tokens.mjs from tokens.json — do not edit.
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;
export type Palette = keyof typeof tokens.color.state;
`;
writeFileSync(join(src, "tokens.ts"), ts);
console.log(`tokens: ${css.length} CSS variables → src/design/tokens.css, src/design/tokens.ts`);
