"""Scenarios (design doc §3, §9).

A ``Scenario`` is a deterministic "world": demand stream, driver supply and
shifts, weather timeline, incidents and per-agent attributes. It is the
**exogenous** part of the simulation — it is *replayed*, identically, for
baseline and treatment. Everything that happens after a platform decision is
generated by behaviour models at run time.

``ScenarioBuilder`` creates scenarios from

* synthetic generators + a preset library (weekday/weekend, AM/PM peak, rain,
  accident, under/over-supply),
* FleetPy demand files (``rq_time,start,end,request_id``),
* generic historical CSVs (lon/lat, planar x/y or node columns),
* zone × hour demand weights (``zonal``, sprint 02 — Hà Nội presets in ``scenarios/hanoi/``).
"""
from __future__ import annotations

import bisect
import csv
import math
import random
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Dict, Hashable, List, Optional, Sequence, Tuple

from kami.network.base import Network
from kami.network.zones import ZoneSystem


@dataclass
class RequestSpec:
    id: int
    t: float
    origin: int
    dest: int
    attrs: Dict[str, Any] = field(default_factory=dict)


@dataclass
class DriverSpec:
    id: int
    loc: int
    shift_start: float
    shift_end: float
    capacity: int = 4
    attrs: Dict[str, Any] = field(default_factory=dict)


@dataclass
class IncidentSpec:
    id: str
    t_start: float
    t_end: float
    center: int                      # node
    radius_m: float = 800.0
    factor: float = 2.5              # travel-time multiplier inside the area
    cancel_multiplier: float = 1.5   # rider cancellation hazard multiplier inside the area


@dataclass
class Scenario:
    name: str
    seed: int
    t_start: float
    t_end: float
    network: Network
    zones: ZoneSystem
    requests: List[RequestSpec]
    drivers: List[DriverSpec]
    weather: List[Tuple[float, str]] = field(default_factory=list)   # (time, state) changes
    incidents: List[IncidentSpec] = field(default_factory=list)
    traffic: Dict[str, Any] = field(default_factory=dict)            # TrafficLayer kwargs
    tags: Dict[str, Any] = field(default_factory=dict)

    def summary(self) -> Dict[str, Any]:
        return {"name": self.name, "seed": self.seed, "hours": (self.t_end - self.t_start) / 3600,
                "requests": len(self.requests), "drivers": len(self.drivers),
                "weather": self.weather, "incidents": [i.id for i in self.incidents]}

    def with_(self, **kw) -> "Scenario":
        return replace(self, **kw)


# Relative demand by hour (synthetic generator). Mean over the day ≈ 1.
DEMAND_PROFILE_WEEKDAY = [0.2, 0.15, 0.1, 0.1, 0.2, 0.5, 1.1, 1.9, 2.0, 1.3, 0.9, 0.9,
                          1.1, 1.0, 0.9, 1.0, 1.3, 1.9, 2.1, 1.6, 1.2, 1.0, 0.7, 0.4]
DEMAND_PROFILE_WEEKEND = [0.5, 0.4, 0.3, 0.2, 0.2, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.4,
                          1.4, 1.3, 1.3, 1.3, 1.4, 1.5, 1.6, 1.6, 1.5, 1.4, 1.1, 0.8]

H = 3600.0

PRESETS: Dict[str, Dict[str, Any]] = {
    "weekday_am_peak": dict(t_start=7 * H, t_end=10 * H, profile="weekday"),
    "weekday_pm_peak": dict(t_start=16.5 * H, t_end=19.5 * H, profile="weekday"),
    "weekday_offpeak": dict(t_start=13 * H, t_end=16 * H, profile="weekday"),
    "weekend": dict(t_start=10 * H, t_end=14 * H, profile="weekend"),
    "rain": dict(t_start=16.5 * H, t_end=19.5 * H, profile="weekday", weather=[(16.5 * H, "rain")],
                 demand_weather_multiplier=1.3),
    "accident": dict(t_start=7 * H, t_end=10 * H, profile="weekday",
                     incidents=[dict(t_offset=0.5 * H, duration=1.0 * H, at="hotspot0", radius_m=1000, factor=3.0)]),
    "undersupply": dict(t_start=7 * H, t_end=10 * H, profile="weekday", supply_multiplier=0.6),
    "oversupply": dict(t_start=13 * H, t_end=16 * H, profile="weekday", supply_multiplier=1.6),
}


class ScenarioBuilder:
    """Factory for scenarios on a fixed network + zone system."""

    def __init__(self, network: Network, zones: ZoneSystem, traffic: Optional[Dict[str, Any]] = None):
        self.network = network
        self.zones = zones
        self.traffic = traffic or {}
        self._nodes = list(network.location_nodes())

    # ------------------------------------------------------------------ attributes
    @staticmethod
    def rider_attrs(rng: random.Random) -> Dict[str, Any]:
        """Individual rider traits drawn from population distributions (design doc §5, level 2)."""
        return {
            "patience_min": rng.lognormvariate(math.log(9.0), 0.45),
            "vot": rng.lognormvariate(math.log(60_000), 0.5),       # VND per hour
            "price_sens": rng.lognormvariate(0.0, 0.3),
            "pool_willingness": rng.gauss(0.0, 0.8),
        }

    @staticmethod
    def driver_attrs(rng: random.Random) -> Dict[str, Any]:
        return {
            "accept_bias": rng.gauss(0.0, 0.5),
            "income_target": rng.lognormvariate(math.log(800_000), 0.3),
        }

    # ------------------------------------------------------------------ spatial sampling
    def _hotspots(self, rng: random.Random, k: int) -> List[Tuple[float, float, float]]:
        x0, y0, x1, y1 = self.network.bounds()
        cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
        spots = [(cx, cy, 2.0)]  # central business district
        for _ in range(k - 1):
            spots.append((rng.uniform(x0, x1), rng.uniform(y0, y1), rng.uniform(0.5, 1.5)))
        return spots

    def _sample_node(self, rng: random.Random, spots, sigma: float, p_hot: float = 0.7) -> int:
        if rng.random() < p_hot:
            w = [s[2] for s in spots]
            sx, sy, _ = spots[_weighted(rng, w)]
            return self.network.nearest_node(rng.gauss(sx, sigma), rng.gauss(sy, sigma))
        return rng.choice(self._nodes)

    # ------------------------------------------------------------------ synthetic
    def synthetic(self, name: str = "synthetic", seed: int = 0, t_start: float = 7 * H, t_end: float = 10 * H,
                  demand_per_hour: float = 200, n_drivers: int = 150, profile: str | Sequence[float] = "weekday",
                  n_hotspots: int = 4, hotspot_sigma_m: float = 900, min_trip_m: float = 1000,
                  weather: Optional[List[Tuple[float, str]]] = None, demand_weather_multiplier: float = 1.0,
                  incidents: Optional[List[Dict[str, Any]]] = None, supply_multiplier: float = 1.0,
                  warmup_s: float = 0.0) -> Scenario:
        """Non-homogeneous Poisson demand around hotspots + shift-based supply.

        ``demand_per_hour`` is the rate at profile value 1.0. ``warmup_s`` starts
        demand earlier than ``t_start`` (metrics should then use ``t_start``).
        """
        rng = random.Random(f"scenario|{name}|{seed}")
        prof = (DEMAND_PROFILE_WEEKDAY if profile == "weekday" else
                DEMAND_PROFILE_WEEKEND if profile == "weekend" else list(profile))
        spots = self._hotspots(rng, n_hotspots)

        # --- demand via thinning
        lam_max = demand_per_hour * max(prof) * demand_weather_multiplier / H
        requests: List[RequestSpec] = []
        t = t_start - warmup_s
        rid = 0
        while True:
            t += rng.expovariate(lam_max)
            if t >= t_end:
                break
            lam = demand_per_hour * prof[int(t // H) % 24] * demand_weather_multiplier / H
            if rng.random() > lam / lam_max:
                continue
            o = self._sample_node(rng, spots, hotspot_sigma_m)
            for _ in range(20):
                d = self._sample_node(rng, spots, hotspot_sigma_m * 1.5, p_hot=0.5)
                if self.network.crow_dist(o, d) >= min_trip_m:
                    break
            requests.append(RequestSpec(rid, round(t, 1), o, d, self.rider_attrs(rng)))
            rid += 1

        # --- supply
        n = max(1, int(round(n_drivers * supply_multiplier)))
        drivers: List[DriverSpec] = []
        span = t_end - (t_start - warmup_s)
        for i in range(n):
            loc = self._sample_node(rng, spots, hotspot_sigma_m * 1.5, p_hot=0.5)
            if rng.random() < 0.7 or span < 2 * H:   # most drivers cover the whole window
                s0, s1 = t_start - warmup_s, t_end
            else:
                length = rng.uniform(0.5, 0.9) * span
                s0 = t_start - warmup_s + rng.uniform(0, span - length)
                s1 = s0 + length
            drivers.append(DriverSpec(i, loc, round(s0, 1), round(s1, 1), attrs=self.driver_attrs(rng)))

        incs = self._incidents(incidents, t_start, spots)

        return Scenario(name, seed, t_start - warmup_s, t_end, self.network, self.zones, requests, drivers,
                        weather=list(weather or []), incidents=incs, traffic=dict(self.traffic),
                        tags={"generator": "synthetic", "profile": profile if isinstance(profile, str) else "custom",
                              "measure_from": t_start})

    def _incidents(self, incidents: Optional[List[Dict[str, Any]]], t_start: float, spots=None) -> List[IncidentSpec]:
        """``at``: ``"hotspot<N>"`` (synthetic only), a node id, or ``{"lon", "lat"}`` (nearest location node)."""
        incs = []
        for k, spec in enumerate(incidents or []):
            at = spec.get("at", "hotspot0")
            if isinstance(at, str) and at.startswith("hotspot"):
                if not spots:
                    raise ValueError(f"incident {k}: 'hotspot' locations need the synthetic generator")
                sx, sy, _ = spots[int(at[7:] or 0) % len(spots)]
                center = self.network.nearest_node(sx, sy)
            elif isinstance(at, dict):
                center = self.node_at_lonlat(float(at["lon"]), float(at["lat"]))
            else:
                center = int(at)
            t0 = t_start + spec.get("t_offset", 0.0)
            incs.append(IncidentSpec(spec.get("id", f"incident{k}"), t0, t0 + spec.get("duration", H), center,
                                     spec.get("radius_m", 800.0), spec.get("factor", 2.5),
                                     spec.get("cancel_multiplier", 1.5)))
        return incs

    def node_at_lonlat(self, lon: float, lat: float) -> int:
        """Nearest location node to a WGS84 point (road networks)."""
        fn = getattr(self.network, "node_at_lonlat", None)
        if fn is not None:
            return fn(lon, lat)
        return self.network.nearest_node(*_lonlat_transformer(self.network)(lon, lat))

    # ------------------------------------------------------------------ zone × hour demand (sprint 02)
    def zonal(self, name: str = "zonal", seed: int = 0, t_start: float = 7 * H, t_end: float = 10 * H,
              demand_per_hour: float = 1000, n_drivers: int = 500, profile: str | Sequence[float] = "weekday",
              weights: Optional[Dict[Hashable, Dict[str, float]]] = None,
              am_hours: Sequence[float] = (6.0, 10.0), pm_hours: Sequence[float] = (16.0, 20.0),
              gravity_lambda_m: float = 3000.0, smoothing: float = 0.1, min_trip_m: float = 1000.0,
              weather: Optional[List[Tuple[float, str]]] = None, demand_weather_multiplier: float = 1.0,
              incidents: Optional[List[Dict[str, Any]]] = None, supply_multiplier: float = 1.0,
              warmup_s: float = 0.0, area: Optional[Sequence[float]] = None) -> Scenario:
        """Non-homogeneous Poisson demand whose pick-ups follow zone weights by time of day (decision D15).

        ``weights``: ``{zone: {"nodes", "residential", "work", "poi"}}`` (``read_zone_weights``); default: node
        counts. A zone's weight is ``count + smoothing × nodes`` with ``count`` = residential buildings in the
        morning peak (``am_hours``), workplaces in the evening peak (``pm_hours``), all kinds otherwise; drop-off
        zones are drawn with the *opposite* weight × ``exp(−distance / gravity_lambda_m)``. Drivers start in zones
        weighted by residential + POI counts. Same parameters + seed → same scenario.

        ``area`` (sprint 03): bounding box ``[lon0, lat0, lon1, lat1]`` (network x/y on networks without lon/lat);
        only zones whose location nodes have their mean point inside it get requests and start vehicles. Vehicles
        still drive on the whole network.
        """
        rng = random.Random(f"zonal|{name}|{seed}")
        prof = (DEMAND_PROFILE_WEEKDAY if profile == "weekday" else
                DEMAND_PROFILE_WEEKEND if profile == "weekend" else list(profile))
        zones = [z for z in sorted(self.zones.zones(), key=str) if self.zones.location_nodes_in(z)]
        if area is not None:
            zones = self._zones_in_area(zones, area)
        if not zones:
            raise ValueError("no zone has location nodes" + (" inside the area" if area is not None else ""))
        counts = {z: dict((weights or {}).get(z) or {}) for z in zones}
        for z in zones:
            counts[z].setdefault("nodes", len(self.zones.nodes_in(z)))

        def w(z, kinds):
            c = counts[z]
            return sum(float(c.get(k, 0.0)) for k in kinds) + smoothing * float(c.get("nodes", 0.0))

        kinds = {"am": (("residential",), ("work",)), "pm": (("work",), ("residential",)),
                 "day": (("residential", "work", "poi"), ("residential", "work", "poi"))}
        if not weights:
            kinds = {k: (("nodes",), ("nodes",)) for k in kinds}
        cum_origin = {k: _cumulative([w(z, o) for z in zones]) for k, (o, _) in kinds.items()}
        dest_w = {k: [w(z, d) for z in zones] for k, (_, d) in kinds.items()}
        centers = [self.zones.centers[z] for z in zones]
        cum_dest: Dict[Tuple[str, int], List[float]] = {}

        def period(t: float) -> str:
            h = (t / H) % 24
            if am_hours[0] <= h < am_hours[1]:
                return "am"
            if pm_hours[0] <= h < pm_hours[1]:
                return "pm"
            return "day"

        def dest_cum(k: str, i: int) -> List[float]:
            key = (k, i)
            hit = cum_dest.get(key)
            if hit is None:
                cx, cy = centers[i]
                hit = cum_dest[key] = _cumulative(
                    [wd * math.exp(-math.hypot(x - cx, y - cy) / gravity_lambda_m)
                     for wd, (x, y) in zip(dest_w[k], centers)])
            return hit

        def node_in(i: int) -> int:
            nodes = self.zones.location_nodes_in(zones[i])
            return nodes[int(rng.random() * len(nodes))]

        lam_max = demand_per_hour * max(prof) * demand_weather_multiplier / H
        requests: List[RequestSpec] = []
        t = t_start - warmup_s
        rid = 0
        while lam_max > 0:
            t += rng.expovariate(lam_max)
            if t >= t_end:
                break
            lam = demand_per_hour * prof[int(t // H) % 24] * demand_weather_multiplier / H
            if rng.random() > lam / lam_max:
                continue
            k = period(t)
            zo = _draw(rng, cum_origin[k])
            o = node_in(zo)
            cum = dest_cum(k, zo)
            for _ in range(20):
                d = node_in(_draw(rng, cum))
                if self.network.crow_dist(o, d) >= min_trip_m:
                    break
            if d == o:
                continue
            requests.append(RequestSpec(rid, round(t, 1), o, d, self.rider_attrs(rng)))
            rid += 1

        n = max(1, int(round(n_drivers * supply_multiplier)))
        cum_home = _cumulative([w(z, ("residential", "poi") if weights else ("nodes",)) for z in zones])
        drivers: List[DriverSpec] = []
        span = t_end - (t_start - warmup_s)
        for i in range(n):
            loc = node_in(_draw(rng, cum_home))
            if rng.random() < 0.7 or span < 2 * H:
                s0, s1 = t_start - warmup_s, t_end
            else:
                length = rng.uniform(0.5, 0.9) * span
                s0 = t_start - warmup_s + rng.uniform(0, span - length)
                s1 = s0 + length
            drivers.append(DriverSpec(i, loc, round(s0, 1), round(s1, 1), attrs=self.driver_attrs(rng)))

        return Scenario(name, seed, t_start - warmup_s, t_end, self.network, self.zones, requests, drivers,
                        weather=list(weather or []), incidents=self._incidents(incidents, t_start),
                        traffic=dict(self.traffic),
                        tags={"generator": "zonal", "profile": profile if isinstance(profile, str) else "custom",
                              "measure_from": t_start, "weighted": bool(weights)})

    def _zones_in_area(self, zones: List[Hashable], area: Sequence[float]) -> List[Hashable]:
        x0, y0, x1, y1 = (float(v) for v in area)
        net = self.network
        lonlat = getattr(net, "lonlats", None)
        out = []
        for z in zones:
            nodes = self.zones.location_nodes_in(z)
            pts = None
            if lonlat is not None:
                try:
                    pts = lonlat(nodes)
                except (ImportError, ValueError):
                    pts = None
            if pts is None or (pts and pts[0] is None):
                pts = [net.coords(n) for n in nodes]
            cx = sum(p[0] for p in pts) / len(pts)
            cy = sum(p[1] for p in pts) / len(pts)
            if x0 <= cx <= x1 and y0 <= cy <= y1:
                out.append(z)
        return out

    def preset(self, preset: str, seed: int = 0, demand_per_hour: float = 200, n_drivers: int = 150,
               **overrides) -> Scenario:
        if preset not in PRESETS:
            raise KeyError(f"unknown preset {preset}; available: {sorted(PRESETS)}")
        kw = dict(PRESETS[preset])
        kw.update(overrides)
        sc = self.synthetic(name=preset, seed=seed, demand_per_hour=demand_per_hour, n_drivers=n_drivers, **kw)
        sc.tags["preset"] = preset
        return sc

    def library(self, seed: int, presets: Sequence[str] = ("weekday_am_peak", "weekday_offpeak", "rain",
                                                           "accident", "undersupply", "oversupply"),
                **kw) -> List[Scenario]:
        """Minimum scenario library of design doc §9."""
        return [self.preset(p, seed=seed, **kw) for p in presets]

    # ------------------------------------------------------------------ replay
    def from_fleetpy_demand(self, demand_csv: str | Path, name: Optional[str] = None, seed: int = 0,
                            n_drivers: int = 50, t_start: Optional[float] = None, t_end: Optional[float] = None,
                            time_offset: float = 0.0, capacity: int = 4) -> Scenario:
        """Replay a FleetPy demand file (columns ``rq_time,start,end,request_id``; nodes of the same network)."""
        rng = random.Random(f"fleetpy|{demand_csv}|{seed}")
        requests = []
        valid = set(self.network.nodes())
        with open(demand_csv) as f:
            for row in csv.DictReader(f):
                o, d = int(row["start"]), int(row["end"])
                if o not in valid or d not in valid or o == d:
                    continue
                requests.append(RequestSpec(int(row["request_id"]), float(row["rq_time"]) + time_offset, o, d,
                                            self.rider_attrs(rng)))
        requests.sort(key=lambda r: (r.t, r.id))
        t0 = t_start if t_start is not None else (requests[0].t if requests else 0.0)
        t1 = t_end if t_end is not None else (requests[-1].t + 1800 if requests else 3600.0)
        origins = [r.origin for r in requests] or self._nodes
        drivers = [DriverSpec(i, rng.choice(origins), t0, t1, capacity, self.driver_attrs(rng))
                   for i in range(n_drivers)]
        return Scenario(name or Path(demand_csv).stem, seed, t0, t1, self.network, self.zones, requests, drivers,
                        traffic=dict(self.traffic), tags={"generator": "fleetpy_demand", "source": str(demand_csv),
                                                          "measure_from": t0})

    def from_csv(self, path: str | Path, name: Optional[str] = None, seed: int = 0, n_drivers: int = 100,
                 time_col: str = "t", origin: Tuple[str, str] = ("o_x", "o_y"),
                 dest: Tuple[str, str] = ("d_x", "d_y"), coords: str = "xy",
                 t_start: Optional[float] = None, t_end: Optional[float] = None) -> Scenario:
        """Replay historical orders.

        ``coords``: ``"xy"`` (metres in network CRS), ``"node"`` (single column names) or
        ``"lonlat"`` (needs ``pyproj`` and a FleetPy network with ``crs.info``).
        """
        rng = random.Random(f"csv|{path}|{seed}")
        to_xy = None
        if coords == "lonlat":
            to_xy = _lonlat_transformer(self.network)
        requests = []
        with open(path) as f:
            for i, row in enumerate(csv.DictReader(f)):
                if coords == "node":
                    o, d = int(row[origin[0]]), int(row[dest[0]])
                else:
                    ox, oy = float(row[origin[0]]), float(row[origin[1]])
                    dx, dy = float(row[dest[0]]), float(row[dest[1]])
                    if to_xy:
                        ox, oy = to_xy(ox, oy)
                        dx, dy = to_xy(dx, dy)
                    o, d = self.network.nearest_node(ox, oy), self.network.nearest_node(dx, dy)
                if o == d:
                    continue
                attrs = self.rider_attrs(rng)
                if row.get("service_preference"):
                    from kami.shared.config import PREFERENCES
                    pref = row["service_preference"]
                    if pref not in PREFERENCES:
                        raise ValueError(f"requests[{i}].attrs.service_preference: lựa chọn không hợp lệ")
                    attrs["service_preference"] = pref
                for key in ("latest_pickup", "latest_dropoff"):
                    if row.get(key):
                        attrs[key] = float(row[key])
                requests.append(RequestSpec(int(row.get("id", i)), float(row[time_col]), o, d, attrs))
        requests.sort(key=lambda r: (r.t, r.id))
        t0 = t_start if t_start is not None else requests[0].t
        t1 = t_end if t_end is not None else requests[-1].t + 1800
        origins = [r.origin for r in requests]
        drivers = [DriverSpec(i, rng.choice(origins), t0, t1, 4, self.driver_attrs(rng)) for i in range(n_drivers)]
        return Scenario(name or Path(path).stem, seed, t0, t1, self.network, self.zones, requests, drivers,
                        traffic=dict(self.traffic), tags={"generator": "csv", "source": str(path), "measure_from": t0})


def read_zone_weights(path: str | Path) -> Dict[int, Dict[str, float]]:
    """``zone_weights.csv`` written by the OSM pipeline (``zone_id,nodes,residential,work,poi``)."""
    out: Dict[int, Dict[str, float]] = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            out[int(row["zone_id"])] = {k: float(v) for k, v in row.items() if k != "zone_id"}
    return out


def _cumulative(weights: Sequence[float]) -> List[float]:
    acc, out = 0.0, []
    for w in weights:
        acc += max(0.0, w)
        out.append(acc)
    if acc <= 0:
        return [float(i + 1) for i in range(len(weights))]
    return out


def _draw(rng: random.Random, cum: List[float]) -> int:
    return min(bisect.bisect_right(cum, rng.random() * cum[-1]), len(cum) - 1)


def _weighted(rng: random.Random, weights: Sequence[float]) -> int:
    total = sum(weights)
    x = rng.random() * total
    acc = 0.0
    for i, w in enumerate(weights):
        acc += w
        if x < acc:
            return i
    return len(weights) - 1


def _lonlat_transformer(network: Network):
    crs_file = getattr(network, "network_dir", None)
    if crs_file is None:
        raise ValueError("lon/lat input needs a RoadNetwork (base/crs.info)")
    from pyproj import Transformer

    crs = (Path(crs_file) / "base" / "crs.info").read_text().strip()
    tr = Transformer.from_crs("EPSG:4326", crs, always_xy=True)
    return lambda lon, lat: tr.transform(lon, lat)
