// Generated by scripts/build-tokens.mjs from tokens.json — do not edit.
export const tokens = {
  "$description": "kami 0.2 design tokens (sprint 03, S03-4). Single source: scripts/build-tokens.mjs writes tokens.css (CSS custom properties) and tokens.ts (RGB for deck.gl / ECharts). Light mode is the reference; contrast is checked by src/design/tokens.test.ts.",
  "color": {
    "brand": {
      "50": "#E6F7F6",
      "100": "#C2EDEB",
      "200": "#94E0DD",
      "300": "#5ECFCB",
      "400": "#2EC3BF",
      "500": "#0ABAB5",
      "600": "#089A96",
      "700": "#077C79",
      "800": "#065F5D",
      "900": "#044341"
    },
    "neutral": {
      "0": "#FFFFFF",
      "25": "#FBFCFC",
      "50": "#F5F7F8",
      "100": "#ECEFF1",
      "200": "#DDE2E6",
      "300": "#C5CDD3",
      "400": "#9AA5B1",
      "500": "#7B8794",
      "600": "#52606D",
      "700": "#3E4C59",
      "800": "#323F4B",
      "900": "#1F2933"
    },
    "bg": "#F5F7F8",
    "surface": "#FFFFFF",
    "surface-muted": "#F5F7F8",
    "border": "#DDE2E6",
    "border-strong": "#C5CDD3",
    "text": "#1F2933",
    "text-muted": "#52606D",
    "text-subtle": "#7B8794",
    "text-on-primary": "#FFFFFF",
    "primary": "#077C79",
    "primary-hover": "#065F5D",
    "accent": "#0ABAB5",
    "accent-soft": "#E6F7F6",
    "focus": "#089A96",
    "link": "#077C79",
    "success": "#089A96",
    "danger": "#C92A2A",
    "danger-soft": "#FDECEC",
    "warning": "#B54708",
    "map-ground": "#F3F4F2",
    "map-water": "#D4EEED",
    "state": {
      "A": {
        "idle": "#7A7F87",
        "cruising": "#C77700",
        "pickup": "#3B5BDB",
        "on_trip": "#D6336C",
        "reposition": "#7048E8"
      },
      "B": {
        "idle": "#7A7F87",
        "cruising": "#C77700",
        "pickup": "#0077BB",
        "on_trip": "#CC3311",
        "reposition": "#AA3377"
      }
    }
  },
  "font": {
    "family": "var(--font-inter), 'Inter', system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
    "family-mono": "ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace",
    "size": {
      "xs": "12px",
      "sm": "13px",
      "md": "14px",
      "lg": "16px",
      "xl": "20px",
      "2xl": "28px"
    },
    "weight": {
      "regular": "400",
      "medium": "500",
      "semibold": "600",
      "bold": "700"
    },
    "line": {
      "tight": "1.2",
      "normal": "1.45"
    }
  },
  "space": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px"
  },
  "radius": {
    "sm": "6px",
    "md": "10px",
    "lg": "14px",
    "full": "999px"
  },
  "shadow": {
    "sm": "0 1px 2px rgba(31, 41, 51, 0.06), 0 1px 3px rgba(31, 41, 51, 0.08)",
    "md": "0 4px 12px rgba(31, 41, 51, 0.08), 0 2px 4px rgba(31, 41, 51, 0.06)"
  },
  "motion": {
    "fast": "150ms",
    "normal": "250ms",
    "easing": "cubic-bezier(0.2, 0, 0, 1)"
  },
  "contrast": {
    "$description": "Pairs checked by tokens.test.ts: [foreground, background, minimum ratio]",
    "text": [
      [
        "text",
        "surface",
        4.5
      ],
      [
        "text",
        "bg",
        4.5
      ],
      [
        "text-muted",
        "surface",
        4.5
      ],
      [
        "text-muted",
        "bg",
        4.5
      ],
      [
        "text-on-primary",
        "primary",
        4.5
      ],
      [
        "text-on-primary",
        "primary-hover",
        4.5
      ],
      [
        "link",
        "surface",
        4.5
      ],
      [
        "primary",
        "accent-soft",
        4.5
      ],
      [
        "danger",
        "surface",
        4.5
      ],
      [
        "text",
        "accent-soft",
        4.5
      ],
      [
        "text-subtle",
        "surface",
        3
      ]
    ],
    "graphics": [
      [
        "success",
        "surface",
        3
      ],
      [
        "danger",
        "surface",
        3
      ],
      [
        "focus",
        "surface",
        3
      ],
      [
        "focus",
        "bg",
        3
      ],
      [
        "primary",
        "surface",
        3
      ]
    ]
  }
} as const;
export type Palette = keyof typeof tokens.color.state;
